version: "3.3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /usr/share/nginx/html

  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

