version: "3.3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /usr/share/nginx/html

  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

  mariadb:
    image: mariadb:latest
    container_name: data_base
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: name_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      8080:80
    environment:
      PMA_HOST: 127.0.0.1:3306
      PMA_USER: username
      PMA_PASSWORD: password